export const routes = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/pages/LoginPage.vue'),
    meta: { requiresAuth: false, layout: 'blank' },
  },
  {
    path: '/registro',
    name: 'Register',
    component: () => import('@/pages/RegisterPage.vue'),
    meta: { requiresAuth: false, layout: 'blank' },
  },
  {
    path: '/',
    name: 'Dashboard',
    component: () => import('@/pages/DashboardPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/vehiculos',
    name: 'Vehicles',
    component: () => import('@/pages/VehiclesListPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/vehiculos/nuevo',
    name: 'VehicleCreate',
    component: () => import('@/pages/VehicleCreatePage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/vehiculos/:id',
    name: 'VehicleDetail',
    component: () => import('@/pages/VehicleDetailPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/vehiculos/:id/edit',
    name: 'VehicleEdit',
    component: () => import('@/pages/VehicleEditPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/conductores',
    name: 'Drivers',
    component: () => import('@/pages/DriversListPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/conductores/nuevo',
    name: 'DriverCreate',
    component: () => import('@/pages/DriverCreatePage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/conductores/:id',
    name: 'DriverDetail',
    component: () => import('@/pages/DriverDetailPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/conductores/:id/edit',
    name: 'DriverEdit',
    component: () => import('@/pages/DriverEditPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/rutas',
    name: 'Routes',
    component: () => import('@/pages/RoutesListPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/mantenimiento',
    name: 'Maintenance',
    component: () => import('@/pages/MaintenanceListPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/combustible',
    name: 'Fuel',
    component: () => import('@/pages/FuelListPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/cargas',
    name: 'Cargo',
    component: () => import('@/pages/CargoListPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/tacografos',
    name: 'Tachographs',
    component: () => import('@/pages/TachographsPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/alertas',
    name: 'Alerts',
    component: () => import('@/pages/AlertsListPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/documentacion',
    name: 'Documents',
    component: () => import('@/pages/DocumentsListPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/informes',
    name: 'Reports',
    component: () => import('@/pages/ReportsListPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/configuracion',
    name: 'Settings',
    component: () => import('@/pages/SettingsPage.vue'),
    meta: { requiresAuth: true },
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'NotFound',
    component: () => import('@/pages/NotFoundPage.vue'),
    meta: { requiresAuth: false },
  },
]
