<template>
  <div class="generated-documents-table">
    <!-- Desktop: VDataTableServer -->
    <VDataTableServer
      :headers="headers"
      :items="items"
      :loading="loading"
      :items-length="pagination.total"
      :items-per-page="pagination.pageSize"
      :items-per-page-options="[15, 25, 50, 100]"
      :page="pagination.page"
      :sort-by="[{ key: pagination.sortBy, order: pagination.sortAsc ? 'asc' : 'desc' }]"
      hover
      class="elevation-1"
      @update:options="onOptionsUpdate"
    >
      <!-- Document type -->
      <template #item.document_type="{ item }">
        <div class="d-flex align-center ga-2">
          <VIcon :icon="getDocTypeIcon(item.document_type)" size="small" />
          {{ getDocTypeLabel(item.document_type) }}
        </div>
      </template>

      <!-- Route -->
      <template #item.route="{ item }">
        <RouterLink
          v-if="item.routes?.id"
          :to="{ name: 'RouteDetail', params: { id: item.routes.id } }"
          class="text-primary"
        >
          {{ item.routes?.origin_city || '—' }} → {{ item.routes?.destination_city || '—' }}
        </RouterLink>
        <span v-else class="text-medium-emphasis">
          {{ item.routes?.origin_city || '—' }} → {{ item.routes?.destination_city || '—' }}
        </span>
      </template>

      <!-- Cargo -->
      <template #item.cargo="{ item }">
        <span v-if="cargoDescription(item)" class="text-body-2">
          {{ cargoDescription(item) }}
        </span>
        <span v-else class="text-medium-emphasis">—</span>
      </template>

      <!-- Generated at -->
      <template #item.generated_at="{ item }">
        {{ formatDateTime(item.generated_at) }}
      </template>

      <!-- Generated by -->
      <template #item.generated_by="{ item }">
        {{ item.generated_by || '—' }}
      </template>

      <!-- File -->
      <template #item.file="{ item }">
        <VBtn
          v-if="item.file_url"
          variant="text"
          size="small"
          prepend-icon="mdi-download"
          @click="$emit('action', { action: 'download', item })"
        >
          {{ item.file_name || 'Descargar' }}
        </VBtn>
        <span v-else class="text-medium-emphasis">—</span>
      </template>

      <!-- Actions -->
      <template #item.actions="{ item }">
        <VBtn
          variant="text"
          icon="mdi-download"
          size="x-small"
          data-testid="action-download"
          @click.stop="$emit('action', { action: 'download', item })"
        />
        <VBtn
          variant="text"
          icon="mdi-delete"
          size="x-small"
          color="error"
          data-testid="action-delete"
          @click.stop="$emit('action', { action: 'delete', item })"
        />
      </template>

      <!-- Loading -->
      <template #loading>
        <VSkeletonLoader type="table-row@5" />
      </template>

      <!-- No data -->
      <template #no-data>
        <div class="text-center pa-8">
          <v-icon size="48" color="grey">mdi-file-document-outline</v-icon>
          <p class="text-body-1 mt-4 text-medium-emphasis">
            Genere documentos de transporte desde una ruta o carga.
          </p>
        </div>
      </template>
    </VDataTableServer>

    <!-- Mobile: Cards -->
    <div class="d-none d-sm-none d-md-none d-lg-none d-xl-none">
      <VCard v-for="doc in items" :key="doc.id" class="mb-2" variant="outlined">
        <VCardText>
          <div class="d-flex justify-space-between align-center">
            <div>
              <div class="text-subtitle-2">
                {{ getDocTypeLabel(doc.document_type) }}
              </div>
              <div class="text-caption text-medium-emphasis">
                {{ doc.routes?.origin_city }} → {{ doc.routes?.destination_city }}
              </div>
            </div>
            <VBtn
              v-if="doc.file_url"
              variant="text"
              icon="mdi-download"
              size="small"
              @click="$emit('action', { action: 'download', item: doc })"
            />
          </div>
          <div class="text-caption mt-2">Generado: {{ formatDateTime(doc.generated_at) }}</div>
        </VCardText>
      </VCard>
    </div>
  </div>
</template>

<script setup>
/**
 * FleetControl — Generated Documents Table
 *
 * Server-side paginated table of generated transport documents.
 * Desktop: VDataTableServer | Mobile: Card list
 *
 * @see docs/plans/feature-documentos-centralizados-plan.md — Fase 4
 */

import { computed } from 'vue'
import { TRANSPORT_DOCUMENT_TYPES } from '@/constants/transport-document-types.js'

const transportDocTypes = Object.values(TRANSPORT_DOCUMENT_TYPES)

defineProps({
  items: { type: Array, required: true },
  loading: { type: Boolean, default: false },
  pagination: {
    type: Object,
    required: true,
  },
})

const emit = defineEmits(['action', 'update:pagination'])

const headers = computed(() => [
  { title: 'Tipo', key: 'document_type', value: 'document_type' },
  { title: 'Ruta', key: 'route', sortable: false },
  { title: 'Carga', key: 'cargo', sortable: false },
  { title: 'Fecha generación', key: 'generated_at', value: 'generated_at' },
  { title: 'Generado por', key: 'generated_by', value: 'generated_by' },
  { title: 'Archivo', key: 'file', sortable: false },
  { title: 'Acciones', key: 'actions', sortable: false },
])

function formatDateTime(dateStr) {
  if (!dateStr) return '—'
  const d = new Date(dateStr)
  return d.toLocaleString('es-ES')
}

function getDocTypeLabel(type) {
  const found = transportDocTypes.find(t => t.key === type || t.type === type)
  return found ? found.label : type || '—'
}

function getDocTypeIcon(type) {
  const found = transportDocTypes.find(t => t.key === type || t.type === type)
  return found?.icon || 'mdi-file-document-outline'
}

function onOptionsUpdate(options) {
  const sortBy = options.sortBy?.[0]?.key || 'generated_at'
  const sortAsc = options.sortBy?.[0]?.order === 'asc'
  emit('update:pagination', {
    page: options.page,
    pageSize: options.itemsPerPage,
    sortBy,
    sortAsc,
  })
}

function cargoDescription(item) {
  return item.routes?.cargo_records?.[0]?.description || item.cargo_records?.description || null
}
</script>
